#!/bin/sh
# Start
## Dnf setup
sudo echo """
fastestmirror=True
max_parallel_downloads=10
defaultyes=True
keepcache=True
""" | sudo tee -a /etc/dnf/dnf.conf

sudo dnf clean dbcache

## RPM Fusion
sudo dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf -y install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

## Upgrade
sudo dnf -y upgrade

# Remove
sudo dnf -y remove \
gnome-tour \
libreoffice* \
gnome-help \
rhythmbox \
gnome-connections \
mediawriter
sudo dnf -y autoremove

# Install
## Fedora
sudo dnf install \
vim \
htop \
zsh

## Flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install -y \
com.brave.Browser \
com.calibre_ebook.calibre \
com.github.tchx84.Flatseal \
com.mattjakeman.ExtensionManager \
com.valvesoftware.Steam \
org.prismlauncher.PrismLauncher \
org.gnome.Boxes \
com.obsproject.Studio \
io.github.zen_browser.zen \
org.onlyoffice.desktopeditors \
de.haeckerfelix.Fragments
